# Generated by Django 4.2.7 on 2025-04-25 09:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_num', models.PositiveBigIntegerField(default=app.models.generate_unique_number, unique=True, verbose_name='Report Number')),
                ('type_report', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=255, verbose_name='Type of Report')),
                ('priority', models.IntegerField(choices=[('LOW', 1), ('MEDIUM', 2), ('HIGH', 3)], verbose_name='Priority')),
                ('name', models.CharField(max_length=255, verbose_name='Report Name')),
                ('status_report', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=255, verbose_name='Status of Report')),
                ('description', models.TextField(verbose_name='Report Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
