# Generated by Django 4.2.7 on 2025-04-28 07:11

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_num', models.PositiveBigIntegerField(default=app.models.generate_unique_number, unique=True, verbose_name='Report Number')),
                ('type_report', models.CharField(choices=[('Information', 'Information'), ('Warning', 'Warning'), ('Error', 'Error')], max_length=255, verbose_name='Type of Report')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], verbose_name='Priority')),
                ('name', models.CharField(max_length=255, verbose_name='Report Name')),
                ('status_report', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=255, verbose_name='Status of Report')),
                ('description', models.TextField(verbose_name='Report Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_category', to='app.category', verbose_name='Category')),
                ('tag', models.ManyToManyField(related_name='report_tag', to='app.tags', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
