name: Check Code Style

on:
  push:
    branches:
      - main
      - dev

jobs:
  PEP8_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff isort

    - name: Check code with ruff
      run: ruff check . --fix

    - name: Check import order with isort
      run: isort .

    - name: Finish
      run: echo "Code style checks passed"
